import img from '../assets/ashwani.png'
export const teamdata=[
    {name: "Anshul Gupta",  designation: "CEO, Co-Founder",img:img}, 
    {name: "Tushar Bhargava",  designation:"CLO, Co-Founder",img:img}, 
    {name: "Angsuman Ray",  designation: "CTO",img:img},
    {name: "Vishal Dhiman",  designation: "IT Product Manager",img:img}, 
    {name: "Wasique Ansari",  designation: "Sr. Backend Developer",img:img}, 
    {name: "Aniket Rathore",  designation: "Sr. Backend Developer",img:img},
    {name: "Monojit Das",  designation: "Frontend Developer",img:img}, 
    {name: "Madhuri Raghorty",  designation: "Product Manager",img:img}, 
    {name: "Ashwani Sharma",  designation: "Frontend Developer",img:img},
    {name: "Pratyush Mahapatra",  designation: "Frontend Developer Intern",img:img}, 
    {name: "Vijit Shrivastava",  designation: "Frontend Developer",img:img}, 
    {name: "Anamika Singh ",  designation: "QA Tester",img:img},
    {name: "Abhishek Kathal",  designation: "Backend Developer",img:img}, 
    {name: "Shreyanshu Shekhar",  designation: "Frontend Developer",img:img}, 
    {name: "Mohit Sharma",  designation: "Assistant Product Manager",img:img},
    {name: "Himanshu Chillar",  designation: "Digital Marketing Executive",img:img},
    {name: "Akriti Garg",  designation: "Communications Lead",img:img}, 
    {name: "Akshay Sinha",  designation: "Customer Success Head",img:img}, 
    {name: "Nivedita Arora",  designation: "Sales Development Executive",img:img}, 
    {name: "Anu Saini ",  designation: "Admin Support",img:img}, 
    {name: "Anup",  designation: "Executive (Finance)",img:img}, 
    {name: "Amit Arora",  designation: "UI/UX Designer",img:img},
  ]